const A = {
    // Change theme
    REQ_CHANGE_THEME: 'REQ_CHANGE_THEME',
    REC_CHANGE_THEME: 'REC_CHANGE_THEME',
    REC_CHANGE_THEME_ERR: 'REC_CHANGE_THEME_ERR',
    RESET_CHANGE_THEME: 'RESET_CHANGE_THEME',

    REQ_DEVICE_THEME: 'REQ_DEVICE_THEME',
    REC_DEVICE_THEME: 'REC_DEVICE_THEME',
    REC_DEVICE_THEME_ERR: 'REC_DEVICE_THEME_ERR',
    RESET_DEVICE_THEME: 'RESET_DEVICE_THEME',
}

export default A
